name: Elixir CI

# Define workflow that runs when changes are pushed to the
# `main` branch or pushed to a PR branch that targets the `main`
# branch. Change the branch name if your project uses a
# different name for the main branch like "master" or "production".
on:
  push:
    branches:
      - main
      - "v*.*"
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Test on OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}} / phx_new ${{matrix.phx_new}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.18.4-otp-26"
              otp: "26.2.5.13"
            phx_new: "1.8.0-rc.3"
          - pair:
              elixir: "1.18.4-otp-27"
              otp: "27.3.4.1"
            phx_new: "1.8.0-rc.3"
            lint: lint
          - pair:
              elixir: "1.18.4-otp-27"
              otp: "27.3.4.1"
            phx_new: "1.7.21"
    steps:
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache deps
        id: cache-deps
        uses: actions/cache@v4
        env:
          cache-name: cache-elixir-deps
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{matrix.pair.otp}}-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.otp}}-${{ env.cache-name }}-

      - name: Cache compiled build
        id: cache-build
        uses: actions/cache@v4
        env:
          cache-name: cache-compiled-build
        with:
          path: _build
          key: ${{ runner.os }}-mix-${{matrix.pair.otp}}-${{matrix.pair.elixir}}-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.otp}}-${{matrix.pair.elixir}}-${{ env.cache-name }}-
            ${{ runner.os }}-mix-${{matrix.pair.otp}}-${{matrix.pair.elixir}}-
            ${{ runner.os }}-mix-${{matrix.pair.otp}}-
            ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get --check-locked

      - name: Install test dependency
        run: mix archive.install hex phx_new ${{matrix.phx_new}} --force

      - name: Run a bunch of useful elixir level checks
        run: mix checks

      - run: mix deps.compile

      - run: mix compile --no-optional-deps --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix test --slowest 5 --color
        if: ${{ ! matrix.lint }}

      - run: mix test --slowest 5 --warnings-as-errors --color
        if: ${{ matrix.lint }}
